### ISSUE TITLE
Update test scenarios for Calendar

### ISSUE THREAD

**Issue by itswillta** [linagora/gatling-openpaas#1]
Users and events need to be provisioned first before running the performance tests. You can do the provisioning steps with help of https://github.com/huy-ta/openpaas-provisioning.

#### To-do list

* [ ]  Refactor event search test(s)
* [ ]  Add Event CRUD tests
* [ ]  Add Calendar CRUD tests
* [ ]  Add test cases for event CRUD with (lots of) attendees
* [ ]  Add test cases for recurrent events
* [ ]  The endpoints need to be changed once the web frontend makes direct requests to Sabre
* [ ]  Integration with OIDC
* [ ]  Instructions to run the performance tests
